language: generic

sudo: required
services:
    - docker


before_install:
    - docker build -t jc-prz/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true jc-prz/docker-react npm run test -- --coverage